/* sha256.c -- an app that hashes text with SHA-256: built for Zknh
 * (make freertos-app NAME=sha256 MARCH=rv32im_zba_zbb_zbkb_zbkx_zbs_zknh), each sigma and
 * Sigma of the hash is one Zknh instruction; built for rv32i (the default), the same source
 * computes them in C (std/include/sha256.h and zknh.h). Both builds print the same digests.
 *
 *   hades> run abc
 *   sha256: self-test 4 of 4 NIST vectors: PASS (Zknh)
 *   sha256: 4096 bytes in ... cycles, ... cycles per byte (Zknh)
 *   ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad  abc
 *   app: sha256 exited with code 0 after ... cycles
 *
 * Every run first checks the SHA-256 examples of NIST (the empty message, "abc" and the
 * 448-bit message, and the 448-bit message again, fed in pieces) and times the hash of 4096
 * generated bytes. With arguments it then prints the digest of the arguments joined by single
 * spaces, in the layout of sha256sum; without, it reads lines (echoed, with Backspace) and
 * prints the digest of each, until an empty line. The exit code is the number of failed
 * self-tests. */
#include <stdint.h>
#include "hades_app.h"
#include "sha256.h"

#if defined( __riscv_zknh )
    #define SHA_HOW    "Zknh"
#else
    #define SHA_HOW    "C"
#endif

#define SHA_LINE_MAX     80
#define SHA_SPEED_BYTES  4096u

static const char acM448[] = "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq";

/* The digests of NIST's examples (FIPS 180-4; the empty message is CAVP's Len = 0). */
static const uint8_t aucNist[ 3 ][ 32 ] =
{
    { 0xe3, 0xb0, 0xc4, 0x42, 0x98, 0xfc, 0x1c, 0x14, 0x9a, 0xfb, 0xf4, 0xc8, 0x99, 0x6f, 0xb9, 0x24,
      0x27, 0xae, 0x41, 0xe4, 0x64, 0x9b, 0x93, 0x4c, 0xa4, 0x95, 0x99, 0x1b, 0x78, 0x52, 0xb8, 0x55 },
    { 0xba, 0x78, 0x16, 0xbf, 0x8f, 0x01, 0xcf, 0xea, 0x41, 0x41, 0x40, 0xde, 0x5d, 0xae, 0x22, 0x23,
      0xb0, 0x03, 0x61, 0xa3, 0x96, 0x17, 0x7a, 0x9c, 0xb4, 0x10, 0xff, 0x61, 0xf2, 0x00, 0x15, 0xad },
    { 0x24, 0x8d, 0x6a, 0x61, 0xd2, 0x06, 0x38, 0xb8, 0xe5, 0xc0, 0x26, 0x93, 0x0c, 0x3e, 0x60, 0x39,
      0xa3, 0x3c, 0xe4, 0x59, 0x64, 0xff, 0x21, 0x67, 0xf6, 0xec, 0xed, 0xd4, 0x19, 0xdb, 0x06, 0xc1 }
};

/* the speed test's data (words, so that whole blocks are hashed straight from it) */
static uint32_t aulData[ SHA_SPEED_BYTES / 4 ];

static int prvSame( const uint8_t * pucA, const uint8_t * pucB )
{
    int iDiffer = 0;

    for( int i = 0; i < 32; i++ )
    {
        iDiffer |= pucA[ i ] ^ pucB[ i ];
    }

    return iDiffer == 0;
}

/* Prints the digest as 64 lowercase hex digits, without a newline. */
static void prvPrintDigest( const uint8_t * pucDigest )
{
    char acHex[ 65 ];
    static const char acDigits[] = "0123456789abcdef";

    for( int i = 0; i < 32; i++ )
    {
        acHex[ 2 * i ] = acDigits[ pucDigest[ i ] >> 4 ];
        acHex[ 2 * i + 1 ] = acDigits[ pucDigest[ i ] & 0xF ];
    }

    acHex[ 64 ] = '\0';
    app_puts( acHex );
}

/* The four NIST checks; returns the number that failed. */
static int prvSelfTest( void )
{
    static const char * const apcMsg[ 3 ] = { "", "abc", acM448 };
    static const uint32_t aulLen[ 3 ] = { 0, 3, 56 };
    uint8_t aucDigest[ 32 ];
    Sha256_t xCtx;
    int iPassed = 0;

    for( int i = 0; i < 3; i++ )
    {
        sha256( apcMsg[ i ], aulLen[ i ], aucDigest );
        iPassed += prvSame( aucDigest, aucNist[ i ] );
    }

    /* the 448-bit message in pieces of 1, 3, 5, ... bytes */
    sha256_init( &xCtx );

    for( uint32_t ulOff = 0, ulPiece = 1; ulOff < aulLen[ 2 ]; ulPiece += 2 )
    {
        uint32_t ulN = ( ulPiece < aulLen[ 2 ] - ulOff ) ? ulPiece : aulLen[ 2 ] - ulOff;

        sha256_update( &xCtx, acM448 + ulOff, ulN );
        ulOff += ulN;
    }

    sha256_final( &xCtx, aucDigest );
    iPassed += prvSame( aucDigest, aucNist[ 2 ] );

    app_printf( "sha256: self-test %d of 4 NIST vectors: %s (" SHA_HOW ")\n", iPassed,
                ( iPassed == 4 ) ? "PASS" : "FAIL" );
    return 4 - iPassed;
}

/* The cycles of one hash of SHA_SPEED_BYTES generated bytes. */
static void prvSpeed( void )
{
    uint32_t x = 0x2545F491u;
    uint8_t aucDigest[ 32 ];

    for( uint32_t i = 0; i < SHA_SPEED_BYTES / 4; i++ )
    {
        x ^= x << 13;
        x ^= x >> 17;
        x ^= x << 5;
        aulData[ i ] = x;
    }

    const uint64_t ullStart = app_cycles();
    sha256( aulData, SHA_SPEED_BYTES, aucDigest );
    const uint32_t ulCycles = ( uint32_t ) ( app_cycles() - ullStart );
    /* tenths of a cycle per byte, rounded (the shell's formatter has no floating point):
     * 10 * cycles / 4096 with shifts, because GCC 12.2 with Zbs stops with an internal
     * compiler error on the constant 2048 that the division would need for the rounding */
    _Static_assert( SHA_SPEED_BYTES == 4096u, "the shifts below divide by 4096" );
    const uint32_t ulTenths = ( ( ( 10u * ulCycles ) >> 11 ) + 1u ) >> 1;

    app_printf( "sha256: %u bytes in %lu cycles, %lu.%lu cycles per byte (" SHA_HOW ")\n",
                SHA_SPEED_BYTES, ( unsigned long ) ulCycles, ( unsigned long ) ( ulTenths / 10u ),
                ( unsigned long ) ( ulTenths % 10u ) );
}

/* The digest of the arguments joined by single spaces, then the text, as sha256sum prints. */
static void prvHashArgs( int argc, char ** argv )
{
    Sha256_t xCtx;
    uint8_t aucDigest[ 32 ];

    sha256_init( &xCtx );

    for( int i = 1; i < argc; i++ )
    {
        uint32_t ulLen = 0;

        while( argv[ i ][ ulLen ] != '\0' )
        {
            ulLen++;
        }

        if( i > 1 )
        {
            sha256_update( &xCtx, " ", 1 );
        }

        sha256_update( &xCtx, argv[ i ], ulLen );
    }

    sha256_final( &xCtx, aucDigest );
    prvPrintDigest( aucDigest );
    app_puts( " " );

    for( int i = 1; i < argc; i++ )
    {
        app_puts( " " );
        app_puts( argv[ i ] );
    }

    app_putc( '\n' );
}

/* Reads lines and prints the digest of each, until an empty line. */
static void prvHashLines( void )
{
    char acLine[ SHA_LINE_MAX + 1 ];
    uint8_t aucDigest[ 32 ];
    uint32_t ulLength = 0;
    int iPrevious = 0;

    app_puts( "sha256: type lines; an empty line ends\n> " );

    for( ; ; )
    {
        const int c = app_getc( -1 );

        if( ( c == '\n' ) && ( iPrevious == '\r' ) )
        {
            iPrevious = c;   /* the LF of CR LF */
            continue;
        }

        iPrevious = c;

        if( ( c == '\r' ) || ( c == '\n' ) )
        {
            app_putc( '\n' );

            if( ulLength == 0 )
            {
                return;
            }

            acLine[ ulLength ] = '\0';
            sha256( acLine, ulLength, aucDigest );
            prvPrintDigest( aucDigest );
            app_puts( "  " );
            app_puts( acLine );
            app_puts( "\n> " );
            ulLength = 0;
        }
        else if( ( c == '\b' ) || ( c == 0x7F ) )
        {
            if( ulLength > 0 )
            {
                ulLength--;
                app_puts( "\b \b" );
            }
        }
        else if( ( c >= ' ' ) && ( c <= '~' ) && ( ulLength < SHA_LINE_MAX ) )
        {
            acLine[ ulLength++ ] = ( char ) c;
            app_putc( ( char ) c );
        }
    }
}

int main( int argc, char ** argv )
{
    const int iFailed = prvSelfTest();

    prvSpeed();

    if( argc > 1 )
    {
        prvHashArgs( argc, argv );
    }
    else
    {
        prvHashLines();
    }

    return iFailed;
}
